# Generated by Django 4.2.1 on 2023-09-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageoperations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='scanned_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
