# Generated by Django 4.2.1 on 2023-09-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageoperations', '0002_uploadedimage_scanned_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='scanned_number',
            new_name='vehicle_number',
        ),
    ]
